### ISSUE TITLE
Missing PauseManager.cpp

### ISSUE THREAD

**Issue by Tatektoi** [guided-hacking/Age_of_Empires_II_Definitive-Edition#2]
I'm new to git-hub and programming. I know how to compile the program and found out that Pausemanager.cpp was corrupted(not able to open in VS). I tried to download the source as a ZIP and via Git Bash, both times i got the same result. I deleted the "#include PauseManager" and the corrupt cpp file and was able to compile the dll.

I dont know if this is a real issue or not, but i wanted to let you know. Wil test the DLL and let know later if there were any problems.

**Comment by GH-Rake** [comment]
Thanks fixed

https://github.com/guided-hacking/Age_of_Empires_II_Definitive-Edition/commit/48592baf82f27cd569305eca95a5e4b798b82cc7
