### ISSUE TITLE
How tu use this ?

### ISSUE THREAD

**Issue by AntoineTesson** [guided-hacking/Age_of_Empires_II_Definitive-Edition#6]
Hi,

I'm not c++ developer and not familiar with this.
Have u got a readme or something, for make me autonome with ur code.

Or maybe the DLL already make ? 

I want to try this hack on my game.
Thanks

**Comment by the-rich-piana** [comment]
Install Visual Studio. Open this project.

Click Build then go into x64 > Debug > should be a DLL in there if no build errors.

load the DLL into AOE2 with an injector.

**Comment by AntoineTesson** [comment]
Perfect ! i have read Ducmentation,  i will try this week-end to build this.. And after why not increase this soft. have a great night !
