### ISSUE TITLE
Technologies (Researches)

### ISSUE THREAD

**Issue by flanker-d** [guided-hacking/Age_of_Empires_II_Definitive-Edition#7]
Can you add list of researched technologies?

**Comment by BDKPlayer** [comment]
I encourage you to do it yourself and create a PR

**Comment by flanker-d** [comment]
Can you help me to find in-memory location of technologies?

**Comment by BDKPlayer** [comment]
I did spend some time searching for it. All I could find was a Make_Tech_Action that had a timer on how long a reasearch is going on but not what it is researching and when its done. Its located in the actionlist of the building producing that is researching the technology. You can find this location easily by looking at the source code. 

Other than that remember that I created this project to help people learn gamehacking. You will have to put in the effort. If you spent XX amount of hours trying to get something to work and are stuck at a **very specific problem** Im happy to help.

I think this is a important missing feature so if anybody wants to create this feature Im very happy to merge your PR!
