### ISSUE TITLE
Tampering detected

### ISSUE THREAD

**Issue by D2therJ** [guided-hacking/Age_of_Empires_II_Definitive-Edition#9]
any ideas?

**Comment by BDKPlayer** [comment]
Are you running any other software that could cause the issue. Such as an injector? Also when does the problem occur. I have only had this problem when trying to debug using VS.

**Comment by D2therJ** [comment]
I was using a bat file with h injector to inject the build. 

Tampering Detection occurs just after loading into a match. Not after injecting, but when a match begins. Whether single or multiplayer.
